-- See https://wiki.hyprland.org/Configuring/Monitors/
-- TODO: manual review — unexpected token after 'require("/usr/share/hypr/stubs/hl.meta.lua")'
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
	output = "HDMI-A-1",
	mode = "1280x720@50",
	position = "0x0",
	scale = "1",
})

-- Set programs that you use
local terminal = "wezterm"
local filemanager = "thunar"
local menu = "wofi --show drun"
local browser = "zen-browser"

-- Some default env vars.
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
-- env = WLR_DRM_NO_ATOMIC,1 # some nvidia fix
hl.env("MOZ_ENABLE_WAYLAND", "1")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
hl.env("GTK_USE_PORTAL", "1")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_MENU_PREFIX", "arch-")
hl.env("QT_QPA_PLATFORM", "wayland")
hl.env("SLD_VIDEODRIVER", "wayland")
hl.env("XCURSOR_THEME", "catppuccin-mocha-blue")
hl.env("GTK_THEME", "Catppuccin-Dark")
hl.env("PULSE_LATENCY_MSEC", "50")

hl.on("hyprland.start", function()
	hl.exec_cmd("swaync")
	hl.exec_cmd("hyprpm reload -n")
	hl.exec_cmd("/usr/lib/hyprpolkitagent")
	hl.exec_cmd("pactl set-default-sink alsa_output.pci-0000_01_00.1.hdmi-stereo")
	hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("awww-daemon")
	hl.exec_cmd("hyprctl setcursor catppuccin-mocha-blue 24")
	hl.exec_cmd("waybar")
	hl.exec_cmd("swayosd-server")
	hl.exec_cmd("~/.config/hypr/scripts/awww.sh")
	hl.exec_cmd("wpctl set-default alsa_output.pci-0000_01_00.1.hdmi-stereo")
	hl.exec_cmd('gsettings set org.gnome.desktop.interface gtk-theme "catppuccin-mocha-teal-standard+default"')
end)

--[[
####################################
############# PLUGINS ##############
####################################
--]]

package.path = package.path .. ";./?.lua;./?/init.lua"
local smw = require("plugins.split-monitor-workspaces")
-- local hyd = require("plugins.hyprdeck")

smw.setup({
	workspace_count = 10,
	enable_persistent_workspaces = false,
})

--[[
####################################
############# PLUGINS ##############
####################################
--]]

hl.config({
	--[[
	plugin = {
		hyprexpo = {
			label_enable = 0,
			border_color_hover = "rgb(ff9317)",
			border_color_focus = "rgb(ff9317)",
			border_color_current = "rgb(ff9317)",
			bg_col = "rgb(000000)",
		},
	},
  --]]
	input = {
		kb_layout = "us,pl",
		kb_variant = "",
		kb_model = "",
		kb_options = "",
		kb_rules = "",
		follow_mouse = 1,
		touchpad = {
			natural_scroll = false,
		},
		repeat_delay = 200,
		repeat_rate = 40,
		sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.
	},
	general = {
		-- See https://wiki.hyprland.org/Configuring/Variables/ for more
		gaps_in = 5,
		gaps_out = 10,
		border_size = 2,
		col = {
			active_border = { colors = { "rgba(3E5C94ff)", "rgba(287AC7ff)", "rgba(4438B0ff)" }, angle = 70 }, -- 45
			inactive_border = "rgba(262626ee)",
		},
		-- layout = master,
		layout = dwindle,
		-- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
		allow_tearing = false,
	},
	--[[
  group = {
    auto_group = true,
    focus_removed_window = false,
    insert_after_current = true,
    group_on_movetoworkspace = true,

    groupbar = {
      enabled = true,
      render_titles = true,
      scrolling = true,
      middle_click_close = true,

      height = 22,
      font_size = 12,
      font_family = "Sans",
      text_padding = 0,

      gradients = true,
      indicator_height = 0,

      col = {
        active = { colors = { "rgba(3E5C94ff)", "rgba(287AC7ff)", "rgba(4438B0ff)" }, angle = 70 },
       -- active = "rgba(33ccff30)",
        inactive = "rgba(2a2a2a55)",
      },

      text_color = "rgba(ffffffdd)",
      text_color_inactive = "rgba(b0b0b0ff)",

      gradient_rounding = 8,
      gradient_round_only_edges = false,

      gaps_in = 8,
      gaps_out = 5,
      keep_upper_gap = false,
    },
  },
  --]]
	decoration = {
		-- See https://wiki.hyprland.org/Configuring/Variables/ for more
		rounding = 10,
		blur = {
			enabled = true,
			size = 8, -- 3
			passes = 2, -- 6
			new_optimizations = true,
			xray = true,
		},
		-- drop_shadow = no
		-- shadow_range = 4
		-- shadow_render_power = 3
		-- col.shadow = rgba(1a1a1aee)
	},
	animations = {
		enabled = true,
	},
	dwindle = {
		-- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
		-- pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
		preserve_split = true, -- you probably want this
		-- smart_split = yes
	},
	master = {
		-- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
		mfact = 0.5,
	},
	--gestures {
	--  # See https://wiki.hyprland.org/Configuring/Variables/ for more
	--  workspace_swipe = off
	--}
	misc = {
		-- See https://wiki.hyprland.org/Configuring/Variables/ for more
		force_default_wallpaper = -1, -- Set to 0 or 1 to disable the anime mascot wallpapers
		-- exit_window_retains_fullscreen = false,
	},
})

hl.curve("defaultBezier", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })
hl.animation({
	leaf = "windows",
	enabled = true,
	speed = 7,
	bezier = "defaultBezier",
})
hl.animation({
	leaf = "windowsOut",
	enabled = true,
	speed = 7,
	bezier = "default",
	style = "popin 80%",
})
hl.animation({
	leaf = "border",
	enabled = true,
	speed = 10,
	bezier = "default",
})
hl.animation({
	leaf = "borderangle",
	enabled = true,
	speed = 8,
	bezier = "default",
})
hl.animation({
	leaf = "fade",
	enabled = true,
	speed = 7,
	bezier = "default",
})
hl.animation({
	leaf = "workspaces",
	enabled = true,
	speed = 6,
	bezier = "defaultBezier",
})

local mainMod = "SUPER"
hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(filemanager))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd(browser))
hl.bind(mainMod .. " + G", function()
	hl.plugin.hyprexpo.expo("toggle")
end)
hl.bind(mainMod .. " + C", hl.dsp.window.close())
hl.bind(mainMod .. " + F", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + S", hl.dsp.exec_cmd("flameshot gui"))
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("wlogout"))
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd("vesktop"))
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd("hyprlock"))
hl.bind(mainMod .. " + z", hl.dsp.exec_cmd("sh -c 'hyprctl dispatch hy3:makegroup h'"))
hl.bind(mainMod .. " + x", hl.dsp.exec_cmd("sh -c 'hyprctl dispatch hy3:makegroup v'"))
hl.bind(mainMod .. " + SHIFT + K", hl.dsp.exec_cmd("hyprctl switchxkblayout current next"))
hl.bind(mainMod .. " + BracketRight", hl.dsp.exec_cmd("swayosd-client --output-volume raise"))
hl.bind(mainMod .. " + BracketLeft", hl.dsp.exec_cmd("swayosd-client --output-volume lower"))
hl.bind(mainMod .. " + BACKSPACE", hl.dsp.exec_cmd("swayosd-client --output-volume mute-toggle"))
-- hl.bind(mainMod .. " + SHIFT + B", hl.dsp.exec_cmd("sh -c \"killall waybar 2>/dev/null; waybar &\""))

--[[
hl.bind(mainMod .. " + left", hyd.dsp.focus({direction = "left"}))
hl.bind(mainMod .. " + down", hyd.dsp.focus({direction = "down"}))
hl.bind(mainMod .. " + up", hyd.dsp.focus({direction = "up"}))
hl.bind(mainMod .. " + right", hyd.dsp.focus({direction = "right"}))
--]]
hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))

--[[
hl.bind(mainMod .. " + SHIFT + h", hyd.dsp.window.move({direction = "left"}))
hl.bind(mainMod .. " + SHIFT + j", hyd.dsp.window.move({direction = "down"}))
hl.bind(mainMod .. " + SHIFT + k", hyd.dsp.window.move({direction = "up"}))
hl.bind(mainMod .. " + SHIFT + l", hyd.dsp.window.move({direction = "right"}))
--]]
hl.bind(mainMod .. " + SHIFT + h", hl.dsp.window.move({ direction = "left" }))
hl.bind(mainMod .. " + SHIFT + j", hl.dsp.window.move({ direction = "down" }))
hl.bind(mainMod .. " + SHIFT + k", hl.dsp.window.move({ direction = "up" }))
hl.bind(mainMod .. " + SHIFT + l", hl.dsp.window.move({ direction = "right" }))

--[[
hl.bind(mainMod .. " + h", hyd.dsp.focus({direction = "left"}))
hl.bind(mainMod .. " + j", hyd.dsp.focus({direction = "down"}))
hl.bind(mainMod .. " + k", hyd.dsp.focus({direction = "up"}))
hl.bind(mainMod .. " + l", hyd.dsp.focus({direction = "right"}))
--]]
hl.bind(mainMod .. " + h", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + j", hl.dsp.focus({ direction = "down" }))
hl.bind(mainMod .. " + k", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + l", hl.dsp.focus({ direction = "right" }))

hl.define_submap("hyprexpo", function()
	hl.bind("h", function()
		hl.plugin.hyprexpo.kb_focus("left")
	end)
	hl.bind("l", function()
		hl.plugin.hyprexpo.kb_focus("right")
	end)
	hl.bind("k", function()
		hl.plugin.hyprexpo.kb_focus("up")
	end)
	hl.bind("j", function()
		hl.plugin.hyprexpo.kb_focus("down")
	end)
	hl.bind("return", function()
		hl.plugin.hyprexpo.kb_confirm()
	end)
	hl.bind("escape", function()
		hl.plugin.hyprexpo.expo("cancel")
	end)
end)

for i = 1, smw.get_amount_of_workspaces() do
	local n = tostring(i)
	if n == "10" then
		n = "0"
	end
	hl.bind(mainMod .. " +" .. n, smw.workspace(n))
	hl.bind(mainMod .. " + SHIFT +" .. n, smw.move_to_workspace_silent(n))
end

hl.window_rule({
	match = {
		class = "wezterm",
	},
	opacity = "0.85 override 0.85",
	rounding = 12,
	border_size = 0,
})

hl.window_rule({
	match = {
		class = "thunar",
	},
	opacity = "0.85 override 0.85",
	rounding = 12,
})

hl.window_rule({
	match = {
		class = "flameshot",
		title = "flameshot",
	},
	move = "0 0",
	pin = true,
})

hl.window_rule({
	match = {
		class = "flameshot",
		title = "flameshot",
	},
	fullscreen = true,
	float = true,
})

hl.bind(mainMod .. " + mouse_down", smw.cycle_workspaces("next"))
hl.bind(mainMod .. " + mouse_up", smw.cycle_workspaces("prev"))

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())
