[General]
DisplayServer=wayland
GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=layer_shell

[Wayland]
CompositorCommand=kwin_wayland --no-lockscreen

[Theme]
CursorTheme=WhiteSur-Cursors
Font=FiraCode Nerd Font Propo Ret
